// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_fehiYiiL61d6eLnvlyQ3-x2IGyahUI',
    appId: '1:647769920826:web:bf0dab027beea3716bec03',
    messagingSenderId: '647769920826',
    projectId: 'aichat-4e765',
    authDomain: 'aichat-4e765.firebaseapp.com',
    storageBucket: 'aichat-4e765.appspot.com',
    measurementId: 'G-EZ55HXG6X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRV0OAR6X7lkK4wu4Q3fw8kBxYdIXpRgI',
    appId: '1:647769920826:android:ef22bb0a3aac94b06bec03',
    messagingSenderId: '647769920826',
    projectId: 'aichat-4e765',
    storageBucket: 'aichat-4e765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBzEGbswpqDHEef2yf44CmxAb6641WG7Y',
    appId: '1:647769920826:ios:84b7199aeb5a0ed86bec03',
    messagingSenderId: '647769920826',
    projectId: 'aichat-4e765',
    storageBucket: 'aichat-4e765.appspot.com',
    iosClientId: '647769920826-3moj3kcfi7t8pdp0hknpdbgltv5t3ov6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBzEGbswpqDHEef2yf44CmxAb6641WG7Y',
    appId: '1:647769920826:ios:84b7199aeb5a0ed86bec03',
    messagingSenderId: '647769920826',
    projectId: 'aichat-4e765',
    storageBucket: 'aichat-4e765.appspot.com',
    iosClientId: '647769920826-3moj3kcfi7t8pdp0hknpdbgltv5t3ov6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAi',
  );
}
